import { EvaluationReport } from "../schemas/evaluationReport.schema";

export function buildMarkdownReport(report: EvaluationReport): string {
  const lines: string[] = [];

  lines.push(`# ${report.startupName} — PitchSignal MENAP Report`);
  lines.push("");

  lines.push(`## Verdict: ${report.verdict}`);
  lines.push(`**Overall Score: ${report.overallScore}/100**`);
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push("## Why Investors May Say No");
  lines.push("");
  report.topInvestorObjections.forEach((o, i) => {
    lines.push(`### ${i + 1}. ${o.objection}`);
    lines.push("");
    lines.push(`**Why it matters:** ${o.whyItMatters}`);
    lines.push("");
    lines.push(`**How to fix:** ${o.howToFix}`);
    lines.push("");
  });

  lines.push("---");
  lines.push("");

  lines.push("## Score Breakdown");
  lines.push("");
  lines.push(`- **Story Clarity:** ${report.scores.storyClarity}/100`);
  lines.push(`- **Regional Market Fit:** ${report.scores.regionalMarketFit}/100`);
  lines.push(`- **Traction Credibility:** ${report.scores.tractionCredibility}/100`);
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push("## VC-Style Memo");
  lines.push("");
  lines.push(report.vcMemo.summary);
  lines.push("");
  lines.push("**What works:**");
  report.vcMemo.whatWorks.forEach((w) => lines.push(`- ${w}`));
  lines.push("");
  lines.push("**What breaks the pitch:**");
  report.vcMemo.whatBreaksThePitch.forEach((b) => lines.push(`- ${b}`));
  lines.push("");

  lines.push("---");
  lines.push("");

  lines.push("## Top 3 Fixes");
  lines.push("");
  report.topThreeFixes.forEach((f, i) => {
    lines.push(`### ${i + 1}. ${f.title}`);
    lines.push(`- **Action:** ${f.action}`);
    lines.push(`- **Expected impact:** ${f.expectedImpact}`);
    lines.push("");
  });

  lines.push("---");
  lines.push("");

  lines.push("## Improved Pitch");
  lines.push("");
  lines.push(`**One-liner:** ${report.improvedPitch.oneLiner}`);
  lines.push("");
  lines.push(`**Elevator pitch:** ${report.improvedPitch.elevatorPitch}`);
  lines.push("");

  lines.push("---");
  lines.push("");

  // AI Insights section
  if (report.aiInsights) {
    lines.push("## AI Analysis Insights");
    lines.push("");

    if (report.aiInsights.missingFields.length > 0) {
      lines.push("### Missing Details");
      lines.push("Your pitch is missing these key details:");
      report.aiInsights.missingFields.forEach((f) => lines.push(`- ${f}`));
      lines.push("");
    }

    lines.push("### Stage Assessment");
    lines.push(report.aiInsights.stageAssessment);
    lines.push("");

    lines.push("### Key Claims Extracted");
    report.aiInsights.keyClaims.forEach((c) => lines.push(`- ${c}`));
    lines.push("");

    lines.push("### Strengths");
    report.aiInsights.strengths.forEach((s) => lines.push(`- ${s}`));
    lines.push("");

    lines.push("### Weaknesses");
    report.aiInsights.weaknesses.forEach((w) => lines.push(`- ${w}`));
    lines.push("");

    if (report.aiInsights.regionalRedFlags.length > 0) {
      lines.push("### Regional Red Flags");
      report.aiInsights.regionalRedFlags.forEach((r) => lines.push(`- ${r}`));
      lines.push("");
    }

    lines.push("---");
    lines.push("");
  }

  lines.push("## Regional Signals Used");
  lines.push("");
  report.regionalSignalsUsed.forEach((s) => lines.push(`- ${s}`));
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push("*Generated by PitchSignal MENAP — Know why investors may say no before you pitch.*");

  return lines.join("\n");
}
